id = "txtar"
name = "Txtar"
version = "0.2.0"
schema_version = 1
authors = ["Tom Fleet <me@followtheprocess.codes>"]
description = "Language support for txtar files"
repository = "https://github.com/FollowTheProcess/zed-txtar"

[grammars.txtar]
repository = "https://github.com/FollowTheProcess/tree-sitter-txtar"
commit = "71f73a5d547e8cf7dc6ae87942070e31dbb46653"
