id = "txtar"
name = "Txtar"
version = "0.2.1"
schema_version = 1
authors = ["Tom Fleet <me@followtheprocess.codes>"]
description = "Language support for txtar files"
repository = "https://github.com/FollowTheProcess/zed-txtar"

[grammars.txtar]
repository = "https://github.com/FollowTheProcess/tree-sitter-txtar"
commit = "c3a2f892c3166897cbf0ab969228bf90e0549faf"
